### ISSUE TITLE
Fix command line args to prodcue graphs

### ISSUE THREAD

**Issue by NicholasSynovic** [SoftwareSystemsLaboratory/ssl-metrics-github-issues#7]
1. Reject pull request from rsethi21
2. Make sure all command line args work and are optional for output graphs

Graphs
* Open issues (default)
* Closed issues
* Joint (open and closed)

Add examples to README.md

**Comment by JacobSPalmer** [comment]
***Sample***

<h1> h1 </h1>

<h2> h1 </h2>
